# Generated by Django 2.0.5 on 2018-06-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rec_type', models.CharField(choices=[('speech', 'Speech recognition'), ('submarine', "Submarine's distanse recognition")], max_length=15)),
                ('rec_class', models.CharField(default='Unknown', max_length=15)),
                ('rec_score', models.DecimalField(decimal_places=3, max_digits=6)),
                ('sample_rate', models.IntegerField()),
                ('nn_name', models.CharField(max_length=15)),
            ],
        ),
    ]
