# Generated by Django 2.0.5 on 2018-06-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0002_record_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='customer',
            new_name='user',
        ),
    ]
