# Generated by Django 2.0.5 on 2018-06-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0003_auto_20180603_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='filename',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='uuid_filename',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
